import Head from 'next/head'
import Footer from '../components/footer'
import FrontPage from '../components/frontPage'
import Header from '../components/header'
import styles from '../styles/Home.module.css'
import SectionCards from '../components/sectionCards'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by " />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Header/>
      <FrontPage/>
      <SectionCards />
      <Footer/>
    </div>
  )
}
